# Use an official C compiler image
FROM gcc:latest

# Set the working directory in the container
WORKDIR /app

# Copy all files into the container
COPY ./code /app

# Default command to keep the container running
CMD ["bash"]